<?php

namespace UserBundle\Repository;

/**
 * NetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetworkRepository extends \Doctrine\ORM\EntityRepository
{
}
