user_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

user_editProfile:
    path:     /editprofile
    defaults: { _controller: UserBundle:User:editProfile }

user_listNetworks:
   path : /listNetworks
   defaults: {_controller : UserBundle:User:listNetworks}

user_addNetwork:
   path : /addNetwork
   defaults: {_controller : UserBundle:User:addNetwork}

user_addTwitter:
   path : /addTwitter
   defaults : {_controller : UserBundle:User:addTwitter}