offer_homepage:
    path:     /
    defaults: { _controller: OfferBundle:Offer:index }

offer_addOffer:
    path:     /addOffer
    defaults: { _controller: OfferBundle:Offer:addOffer }

offer_showOffer:
    path:     /showOffer/{slug}
    defaults: { _controller: OfferBundle:Offer:showOffer }